### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by luciaesporta** [nogiszd/xiaomi-note-exporter#27]
**Describe the bug**
Hi! First of all, I want to sincerely thank you for creating this alternative. It’s a huge relief to know that a tool like this exists, and I truly appreciate the effort you’ve put into making it available for others. 
 
I’ve successfully downloaded and executed the .exe file, and I’m able to log into my Xiaomi account without any issues. However, when I paste the URL of the Xiaomi Notes page (`https://us.i.mi.com/note/h5#/`), nothing happens, and the notes don’t export. When this happens, the terminal closes and I've to start the process again.

Could you please confirm if this might be a bug or if I’m inputting something incorrectly? I’ve tried several times, but I can’t seem to get past this step.

Thanks again for your time and effort. I’d really appreciate it if you could take a look at this issue!

Best regards,
Lu

**To Reproduce**
1. Download and extract the Xiaomi Note Exporter tool from the repository.
2. Execute the .exe file on a Windows machine.
3. Log in to your Xiaomi account when prompted.
4. Copy the following URL from Xiaomi Notes after successfully logging in via a browser: https://us.i.mi.com/note/h5#/
5. Paste the URL into the input field of the exporter tool and press Enter.
6. Verify how the terminal closes 

**Expected behavior**
The tool should successfully export all available notes from the Xiaomi Notes account into a local folder or file.

**Comment by nogiszd** [comment]
Hello @luciaesporta ,

probably it was issue with too old dependencies, [newest version](https://github.com/nogiszd/xiaomi-note-exporter/releases/tag/v1.3.0) should resolve this.
Please confirm if this was the case, so I can close the issue.

**Comment by arsh-codes** [comment]
I am using the Release v1.3.0 along with latest .net runtime (8). There are no voice notes and 355 notes in total. It is showing '** Unsupported note type (Mind-map or Sound note) (Created at: 4/26/2021 15:21)**'. It was working fine till a month ago. Please check

**Comment by nogiszd** [comment]
@luciaesporta 
Please follow the instructions thoroughly, you do not need to paste any URL after signing in, you only input the desired domain that is usually working for you, as you would access Mi Cloud normally.

Default is: us.i.mi.com, because it's the usual domain for majority of users.

@arsh-codes 
I've checked it twice and it works just fine. Please make sure if you have latest Chrome version installed. You can also download most latest version of the app (v1.4.0).

**Comment by arsh-codes** [comment]
@nogiszd still the same issue, mail me on work.arshdeep@outlook.com and I'll show there.

**Comment by nogiszd** [comment]
Stale issue, closing.
